# Generated by Django 5.0.3 on 2024-04-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cliente_alter_producto_precio_factura_delete_facrura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
