# Generated by Django 5.0.3 on 2024-04-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cliente_hijos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='hijos',
            field=models.IntegerField(),
        ),
    ]
